challenge_id = "sheap"

challenge_name = "Sheap"

challenge_description = '''
TODO: create a description here for
the challenge that is really cool
and interesting
'''

challenge_spoilers = '''
TODO: explain the challenge
here for the commentators
so that they can talk about it
'''

author = "negasora"

hints = [
    "sbrk(0) gives you the end of the heap and seccomp is per-thread :o",
    "You don't need to be precise with your overwrites, sometimes spray and pray is the way :)"
]
